# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: '1.23.10'

    - name: golangci-lint
      uses: golangci/golangci-lint-action@v8
      with:
        version: v2.1

    - name: Fmt
      run: make fmt

    - name: Tidy
      run: make tidy

    - name: Check for diffs
      run: git diff --exit-code

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: '1.23.10'

    - name: Build
      run: make build

    - name: Test
      run: make test

    - name: Upload binary
      uses: actions/upload-artifact@v4
      with:
        name: mdcli
        path: mdcli
